msgid ""
msgstr ""
"Project-Id-Version: oVirt Client\n"
"POT-Creation-Date: 2016-11-02 19:29+0000\n"
"PO-Revision-Date: 2016-11-02 19:31+0000\n"
"Last-Translator: Nicol√°s Kovac Neumann <nicolas@devels.es>\n"
"Language-Team: nicolas@devels.es\n"
"Language: en\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.7.1\n"
"X-Poedit-KeywordsList: _;gettext;gettext_noop\n"
"X-Poedit-Basepath: .\n"
"X-Poedit-SearchPath-0: /home/nico/ovirt_client/ovirt_client\n"

#: /home/nico/ovirt_client/ovirt_client/about.py:51
#: /home/nico/ovirt_client/ovirt_client/credentials.py:90
#: /home/nico/ovirt_client/ovirt_client/credentials.py:94
#: /home/nico/ovirt_client/ovirt_client/credentials.py:164
#: /home/nico/ovirt_client/ovirt_client/credentials.py:178
#: /home/nico/ovirt_client/ovirt_client/credentials.py:260
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:268
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:271
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:277
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:283
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:285
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:289
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:291
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:359
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:399
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:416
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:420
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:441
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:446
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:449
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:451
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:484
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:489
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:630
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:844
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:891
msgid "apptitle"
msgstr "oVirt desktop client"

#: /home/nico/ovirt_client/ovirt_client/about.py:53
msgid "appdesc"
msgstr "A simple oVirt desktop client"

#: /home/nico/ovirt_client/ovirt_client/about.py:56
msgid "written_by"
msgstr "Written by"

#: /home/nico/ovirt_client/ovirt_client/about.py:58
msgid "unofficial_project"
msgstr "This project is unofficial!"

#: /home/nico/ovirt_client/ovirt_client/about.py:63
#: /home/nico/ovirt_client/ovirt_client/credentials.py:228
msgid "ok"
msgstr "OK"

#: /home/nico/ovirt_client/ovirt_client/about.py:84
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:150
msgid "about"
msgstr "About"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:63
msgid "loading"
msgstr "Loading..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:79
msgid "authenticating"
msgstr "Authenticating..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:87
msgid "authenticated_and_storing"
msgstr "Authenticated, storing credentials..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:90
#: /home/nico/ovirt_client/ovirt_client/credentials.py:94
#: /home/nico/ovirt_client/ovirt_client/credentials.py:164
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:277
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:359
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:399
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:420
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:446
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:449
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:630
msgid "error"
msgstr "Something bad happened..."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:90
msgid "ovirt_connection_error"
msgstr "oVirt connection error"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:91
#: /home/nico/ovirt_client/ovirt_client/credentials.py:95
msgid "error_while_authenticating"
msgstr "Error while authenticating"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:94
msgid "ovirt_request_error"
msgstr "oVirt request error"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:106
msgid "storing_credentials"
msgstr "Credentials"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:112
msgid "successfully_authenticated"
msgstr "Successfully authenticated"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:164
msgid "no_empty_creds"
msgstr ""
"Neither username or password might be blank. Please, enter your oVirt "
"credentials."

#: /home/nico/ovirt_client/ovirt_client/credentials.py:178
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:271
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:484
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:844
msgid "confirm"
msgstr "Confirm"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:178
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:844
msgid "confirm_quit"
msgstr "Are you sure you want to quit?"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:212
msgid "username"
msgstr "Username"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:214
msgid "password"
msgstr "Password"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:225
msgid "remember_username_and_password"
msgstr "Remember username and password"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:231
msgid "cancel"
msgstr "Cancel"

#: /home/nico/ovirt_client/ovirt_client/credentials.py:260
msgid "credentials"
msgstr "Credentials"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:87
msgid "no_vms"
msgstr ""
"You have currently no permissions over machines on this oVirt infrastructure"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:138
msgid "refresh"
msgstr "Refresh"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:143
msgid "forget_credentials"
msgstr "Forget credentials"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:155
msgid "exit"
msgstr "Exit"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:206
msgid "up"
msgstr "up"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:208
msgid "down"
msgstr "down"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:210
msgid "powering_down"
msgstr "powering down"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:212
msgid "wait_for_launch"
msgstr "waiting for launch"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:214
msgid "powering_up"
msgstr "powering up"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:216
msgid "rebooting"
msgstr "rebooting"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:230
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:247
msgid "shut_down"
msgstr "shut down"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:232
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:249
msgid "power_on"
msgstr "power on"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:253
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:272
msgid "force_off"
msgstr "force off"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:244
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:271
msgid "current_vm_status"
msgstr "Current virtual machine status is"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:247
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:249
msgid "click_to_action"
msgstr "Click to"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:268
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:285
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:291
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:416
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:451
msgid "warning"
msgstr "Warning"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:268
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:285
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:291
msgid "vm_in_unchangeable_status"
msgstr ""
"Cannot change virtual machine status since it is already performing a power "
"on/shutdown task"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:271
msgid "confirm_vm_status_change"
msgstr "Please, confirm virtual machine status change to"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:293
msgid "confirm_vm_force_off"
msgstr "Please, confirm you want to forcibly power off the virtual machine"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:277
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:446
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:630
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:757
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:769
msgid "unexpected_connection_drop"
msgstr "Connection has been closed unexpectedly. App will close."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:283
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:289
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:489
msgid "success"
msgstr "Success"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:283
msgid "shutting_down_vm"
msgstr "Shutting down machine..."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:289
msgid "vm_not_powered_up"
msgstr "VM is powered off"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:347
msgid "powering_up_vm"
msgstr "Powering up machine..."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:305
#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:355
msgid "force_off_vm"
msgstr "Forcing off machine..."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:359
msgid "unexpected_request_error"
msgstr "An unexpected error was received when trying to request a console"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:359
msgid "check_vm_config_updated"
msgstr ""
"Please, check if the status of the VM is updated in oVirt and, if "
"necessary, poweroff and start the machine"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:399
msgid "no_viewer_file"
msgstr "Could not get viewer configuration file. Please, try again."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:416
msgid "cannot_connect_if_vm_not_up"
msgstr ""
"Cannot start virtual machine if status is not Up. Make sure VM is started "
"first."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:420
msgid "cannot_open_more_viewer_sessions"
msgstr ""
"You're already running a viewer on this machine. No other viewer can be "
"opened at a time."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:441
msgid "info"
msgstr "Information"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:441
msgid "acquiring_vm_from_pool"
msgstr ""
"Allocating a VM from the VmPool. Please be patient. Once the VM is "
"available, it will automatically appear in your dashboard."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:449
msgid "cannot_attach_vm_to_user"
msgstr ""
"Cannot allocate a VM. Either you already have the maximum of assignable VMs "
"or there are no machines left in the VmPool."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:451
msgid "object_is_not_a_vmpool"
msgstr "Selected object is not a VmPool."

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:484
msgid "confirm_forget_creds"
msgstr "Do you really want to forget your stored credentials?"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:489
msgid "creds_forgotten"
msgstr "Credentials successfully dropped"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:507
msgid "vmpool"
msgstr "Virtual machines pool"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:515
msgid "grab_vm_vmpool"
msgstr "Allocate virtual machine"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:564
msgid "connect"
msgstr "Connect to the virtual machine"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:567
msgid "viewer_already_opened"
msgstr "Viewer for this machine is open now"

msgid "force_off_tooltip"
msgstr "Force off the virtual machine"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:647
msgid "total_machines"
msgstr "Number of machines"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:647
msgid "total_vmpools"
msgstr "Number of VmPools"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:689
msgid "auto_logout_warn"
msgstr ""
"If you don't accept this window, you'll be automatically logged out the "
"session within a short amount of time due to inactivity"

#: /home/nico/ovirt_client/ovirt_client/ovirtclient.py:690
msgid "auto_logout_warn_title"
msgstr "oVirt desktop client: Enforced auto-logout"
